delete from abstract_object;
commit;
delete from human_name;
commit;
delete from news;
commit;
delete from street_regions;
commit;
delete from street;
commit;
delete from region;
commit;
delete from district;
commit;
delete from access_user_phone;
commit;
delete from phone;
commit;
delete from access_user;
commit;