
package biz.rageintegro.erealt.domain.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DomainService", targetNamespace = "http://ws.domain.erealt.rageintegro.biz/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DomainService {


    /**
     * 
     * @param caption
     * @return
     *     returns biz.rageintegro.erealt.domain.stub.Holder
     */
    @WebMethod
    @WebResult(name = "district", partName = "district")
    public Holder findDistrictByCaption(
        @WebParam(name = "caption", partName = "caption")
        String caption);

    /**
     * 
     * @param caption
     * @param districtId
     * @return
     *     returns biz.rageintegro.erealt.domain.stub.Holder
     */
    @WebMethod
    @WebResult(name = "region", partName = "region")
    public Holder findRegionByCaption(
        @WebParam(name = "caption", partName = "caption")
        String caption,
        @WebParam(name = "districtId", partName = "districtId")
        long districtId);

    /**
     * 
     * @param caption
     * @param regionId
     * @return
     *     returns biz.rageintegro.erealt.domain.stub.Holder
     */
    @WebMethod
    @WebResult(name = "street", partName = "street")
    public Holder findStreetByCaption(
        @WebParam(name = "caption", partName = "caption")
        String caption,
        @WebParam(name = "regionId", partName = "regionId")
        long regionId);

    /**
     * 
     * @param regionId
     * @return
     *     returns biz.rageintegro.erealt.domain.stub.StreetListResponse
     */
    @WebMethod
    @WebResult(name = "streets", partName = "streets")
    public StreetListResponse findStreetsByRegion(
        @WebParam(name = "regionId", partName = "regionId")
        long regionId);

    /**
     * 
     * @param saleFlat
     */
    @WebMethod
    public void persistSaleFlat(
        @WebParam(name = "saleFlat", partName = "saleFlat")
        SaleFlat saleFlat);

    /**
     * 
     * @param leaseFlat
     */
    @WebMethod
    public void persistLeaseFlat(
        @WebParam(name = "leaseFlat", partName = "leaseFlat")
        LeaseFlat leaseFlat);

    /**
     * 
     * @param saleFlat
     */
    @WebMethod
    public void mergeSaleFlat(
        @WebParam(name = "saleFlat", partName = "saleFlat")
        SaleFlat saleFlat);

    /**
     * 
     * @param leaseHouse
     */
    @WebMethod
    public void mergeLeaseFlat(
        @WebParam(name = "leaseHouse", partName = "leaseHouse")
        LeaseFlat leaseHouse);

    /**
     * 
     * @param saleLand
     */
    @WebMethod
    public void persistSaleLand(
        @WebParam(name = "saleLand", partName = "saleLand")
        SaleLand saleLand);

    /**
     * 
     * @param saleLand
     */
    @WebMethod
    public void mergeSaleLand(
        @WebParam(name = "saleLand", partName = "saleLand")
        SaleLand saleLand);

    /**
     * 
     * @param saleHouse
     */
    @WebMethod
    public void persistSaleHouse(
        @WebParam(name = "saleHouse", partName = "saleHouse")
        SaleHouse saleHouse);

    /**
     * 
     * @param saleHouse
     */
    @WebMethod
    public void mergeSaleHouse(
        @WebParam(name = "saleHouse", partName = "saleHouse")
        SaleHouse saleHouse);

    /**
     * 
     * @param leaseHouse
     */
    @WebMethod
    public void persistLeaseHouse(
        @WebParam(name = "leaseHouse", partName = "leaseHouse")
        LeaseHouse leaseHouse);

    /**
     * 
     * @param leaseHouse
     */
    @WebMethod
    public void mergeLeaseHouse(
        @WebParam(name = "leaseHouse", partName = "leaseHouse")
        LeaseHouse leaseHouse);

    /**
     * 
     * @param caption
     * @return
     *     returns biz.rageintegro.erealt.domain.stub.Holder
     */
    @WebMethod
    @WebResult(name = "humanName", partName = "humanName")
    public Holder findHumanNameByCaption(
        @WebParam(name = "caption", partName = "caption")
        String caption);

    /**
     * 
     * @param eid
     * @param source
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "existEntry", partName = "existEntry")
    public boolean existAbstractObjectByEidAndSource(
        @WebParam(name = "eid", partName = "eid")
        String eid,
        @WebParam(name = "source", partName = "source")
        String source);

    /**
     * 
     * @param eid
     * @param source
     * @param streetId
     * @return
     *     returns biz.rageintegro.erealt.domain.stub.Holder
     */
    @WebMethod
    @WebResult(name = "abstractObject", partName = "abstractObject")
    public Holder findAbstractObjectByStreetIdAndEidAndSource(
        @WebParam(name = "streetId", partName = "streetId")
        long streetId,
        @WebParam(name = "eid", partName = "eid")
        String eid,
        @WebParam(name = "source", partName = "source")
        String source);

    /**
     * 
     * @param phone
     * @return
     *     returns biz.rageintegro.erealt.domain.stub.Holder
     */
    @WebMethod
    @WebResult(name = "accessUser", partName = "accessUser")
    public Holder findAccessUserByPhone(
        @WebParam(name = "phone", partName = "phone")
        Phone phone);

    /**
     * 
     * @param phoneNumber
     * @param code
     * @return
     *     returns biz.rageintegro.erealt.domain.stub.Holder
     */
    @WebMethod
    @WebResult(name = "phone", partName = "phone")
    public Holder findPhone(
        @WebParam(name = "code", partName = "code")
        String code,
        @WebParam(name = "phoneNumber", partName = "phoneNumber")
        int phoneNumber);

    /**
     * 
     * @param accessUser
     */
    @WebMethod
    public void mergeAccessUser(
        @WebParam(name = "accessUser", partName = "accessUser")
        AccessUser accessUser);

    /**
     * 
     * @param accessUser
     */
    @WebMethod
    public void persistAccessUser(
        @WebParam(name = "accessUser", partName = "accessUser")
        AccessUser accessUser);

}
